version: '3.6'
services:
  app:
    container_name: 'combine-app'
    build:
      context: .
    volumes:
      - .:/home/node
      - /home/node/node_modules
    ports:
      - 8080:8080
    networks:
      - local
networks:
  local:
    driver: bridge

volumes:
  app-volume:
