version: '3.6'
services:
  app:
    container_name: 'combine_app'
    build:
      context: .
    env_file:
      - .env.docker
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - local
  mongo:
    container_name: 'combine_mongo'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - local

  mongo-express:
    container_name: 'combine_mongo_express'
    image: mongo-express
    restart: always
    networks:
      - local
    ports:
      - '8001:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  local:
    driver: bridge

volumes:
  app-volume:
