version: '3.6'
services:
  app:
    container_name: 'combine-app'
    build:
      context: .
    env_file:
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    networks:
      - local
networks:
  local:
    driver: bridge

volumes:
  app-volume:
